// src/utils/labels.js

export const labels = {
    en: {
        title: "Kundli Entries",
        addNew: "+ Add New",
        noEntries: "No entries found. Add new kundli above.",
        birthChart: "🔮 Birth Chart for",
        dob: "Date of Birth",
        time: "Time of Birth",
        place: "Place of Birth",
        ascendant: "Ascendant",
        moon: "Moon Sign",
        planets: "Planets",
        houses: "Houses",
        noPlanets: "No planets data available",
        noHouses: "No houses data available",
        show: "Show Chart",
        hide: "Hide Chart",
        edit: "Edit",
        delete: "Delete",
    },
    gu: {
        title: "કુંડળી એન્ટ્રીઓ",
        addNew: "+ નવી ઉમેરો",
        noEntries: "કોઈ એન્ટ્રી મળી નથી. ઉપર નવી કુંડળી ઉમેરો.",
        birthChart: "🔮 જન્મ કુંડળી",
        dob: "જન્મ તારીખ",
        time: "જન્મ સમય",
        place: "જન્મ સ્થળ",
        ascendant: "લગ્ન",
        moon: "ચંદ્ર રાશિ",
        planets: "ગ્રહો",
        houses: "ભાવો",
        noPlanets: "કોઈ ગ્રહોની માહિતી ઉપલબ્ધ નથી",
        noHouses: "કોઈ ભાવોની માહિતી ઉપલબ્ધ નથી",
        show: "ચાર્ટ બતાવો",
        hide: "ચાર્ટ છુપાવો",
        edit: "ફેરફાર",
        delete: "કાઢી નાંખો",
    },
};
